#!/bin/bash

RED="\033[1;31m"
GREEN="\033[1;32m"
NOCOLOR="\033[0m"

mylog() {
        STEP=$1
        MSG=$2

        echo -e "step $STEP: ${GREEN}${MSG}${NOCOLOR}"
        logger "step $STEP: $MSG"
}

myfail() {
        STEP=$1
        MSG=$2

        echo -e "step $STEP ERROR: ${RED}${MSG}${NOCOLOR}"
        logger "step $STEP ERROR: $MSG"
}

# handle command line options
if [[ $1 == "-h" ]]; then
        echo "usage: $0"
        echo " -h prints help"

        exit 1
fi

mylog 1 "step 1: ${GREEN}pre-configuring packages${NOCOLOR}"
sudo dpkg --configure -a

echo

mylog 2 "step 2: ${GREEN}fix and attempt to correct a system with broken dependencies${NOCOLOR}"
sudo apt-get install -f

echo

mylog 3 "step 3: ${GREEN}update apt cache${NOCOLOR}"
sudo apt-get update

echo

mylog 4 "step 4: ${GREEN}upgrade packages${NOCOLOR}"
sudo apt-get upgrade

echo

mylog 5 "step 5: ${GREEN}distribution upgrade${NOCOLOR}"
sudo apt-get dist-upgrade

echo

mylog 6 "step 6: ${GREEN}remove unused packages${NOCOLOR}"
sudo apt-get --purge autoremove

echo

mylog 7 "step 7: ${GREEN}clean up${NOCOLOR}"
sudo apt-get autoclean

# step 3
if [[ $? == 0 ]]; then
        myfail 3 "nothing really"
fi
